export const Select = {
    Fittest,
    FittestLinear,
    FittestRandom,
    Random,
    RandomLinearRank,
    TrueLinearRank,
    Sequential,
    Tournament2,
    Tournament3,
};
export interface GeneticOptions<T> {
    mutationFunction: (phenotype: T) => Promise<T>;
    crossoverFunction: (a: T, b: T) => Promise<Array<T>>;
    fitnessFunction: (phenotype: T, isLast?: boolean) => Promise<{ fitness: number; state?: Record<string, unknown> }>;
    randomFunction: () => Promise<T>;
    populationSize: number;
    mutateProbablity?: number;
    crossoverProbablity?: number;
    fittestNSurvives?: number;
    select1?: (pop: Array<Phenotype<T>>) => T;
    select2?: (pop: Array<Phenotype<T>>) => T;
    deduplicate?: (phenotype: T) => boolean;
    optimize?: (a: Phenotype<T>, b: Phenotype<T>) => boolean;
}

export interface Phenotype<T> {
    fitness: number;
    entity: T;
    state: Record<string, unknown>;
}

/**
 * Genetic algorithm over a fixed fitness landscape.
 *
 * Contract: the `fitnessFunction` must be a pure function of `entity` and
 * any external state captured at construction time. One GA instance =
 * one optimization problem = one dataset. For walk-forward or other
 * dynamic-data workflows, instantiate a separate Genetic per data window
 * and aggregate the winners externally — do NOT mutate inputs to
 * `fitnessFunction` between generations of the same instance.
 *
 * The final answer of a run is `population[0]` after the last
 * `estimate()` call.
 */
export class Genetic<T> {
    public stats = {};
    public options: GeneticOptions<T>;
    public population: Array<Phenotype<T>> = [];
    protected internalGenState = {}; /* Used for random linear */

    constructor(options: GeneticOptions<T>) {
        const defaultOptions: Partial<GeneticOptions<T>> = {
            populationSize: 250,
            mutateProbablity: 0.2,
            crossoverProbablity: 0.9,
            // Default 1: protects against selection-noise regression of
            // population[0] across generations. Elite genome carries forward
            // and is re-evaluated each gen, so the score is always fresh.
            fittestNSurvives: 1,
            select1: Select.Fittest,
            select2: Select.Tournament2,
            optimize: (phenotypeA: Phenotype<T>, phenotypeB: Phenotype<T>) => {
                return phenotypeA.fitness >= phenotypeB.fitness;
            },
        };

        this.options = { ...defaultOptions, ...options };
    }

    /**
     * Startup population. If not passed, will be random-generated by randomFunction().
     */
    public async seed(entities: Array<T> = []) {
        this.population = entities.map((entity) => ({ fitness: null, entity, state: {} }));

        // seed the population
        await this.fill(this.population);
    }

    public best(count = 1) {
        return this.population.slice(0, count);
    }

    /**
     * Breed population.
     *
     * Elitism (v2): elite phenotypes carry their **entity** forward; their
     * `fitness` and `state` are reset to null so the next estimate() always
     * rescores against the current fitness landscape. Combined with the
     * "one run = one dataset" contract, this means population[0] is always
     * a meaningful answer after estimate().
     */
    public async breed() {
        const elitePhenotypes: Array<Phenotype<T>> = [];

        if (this.options.fittestNSurvives) {
            const top = this.population.slice(0, this.options.fittestNSurvives);
            for (const ph of top) {
                // Carry genome forward, reset score so it's rescored against
                // the current external state (dataset, market window, etc).
                elitePhenotypes.push({ fitness: null, entity: ph.entity, state: {} });
            }
        }

        let newPop: Array<Phenotype<T>> = [];
        const maxAttempts = this.options.populationSize * 10;
        let attempts = 0;

        while (newPop.length < this.options.populationSize && attempts < maxAttempts) {
            const crossed = await this.tryCrossover();
            if (crossed.length === 0) {
                attempts++;
                continue;
            }
            newPop.push(...crossed.map((entity) => ({ fitness: null, entity, state: {} })));
            attempts++;
        }

        if (this.options.deduplicate) {
            newPop = newPop.filter((ph) => this.options.deduplicate(ph.entity));
        }

        newPop = [...elitePhenotypes, ...newPop];

        if (newPop.length > this.options.populationSize) {
            newPop = newPop.slice(0, this.options.populationSize);
        }

        await this.fill(newPop);
        this.population = newPop;
    }

    /**
     * Estimate population before breeding.
     *
     * Every phenotype is evaluated each call — fitness is never cached
     * across generations. After this call, `population[0]` is the best
     * phenotype on the current fitness landscape.
     *
     * Contract: `fitnessFunction` must return `{ fitness: number }` where
     * `fitness` is a finite number (no `NaN`, no `Infinity`). Non-finite
     * values throw a descriptive error instead of silently corrupting the
     * sort order downstream.
     */
    public async estimate() {
        const { fitnessFunction } = this.options;
        // reset for each generation
        this.internalGenState = {};

        const tasks = await Promise.all(
            this.population.map(({ entity }, idx) => {
                const isLast = idx === this.population.length - 1;
                return fitnessFunction(entity, isLast);
            }),
        );

        for (let i = 0; i < this.population.length; i++) {
            const target = this.population[i];
            const result = tasks[i];
            if (!result || typeof result.fitness !== 'number' || !Number.isFinite(result.fitness)) {
                throw new Error(
                    `fitnessFunction returned a non-finite fitness for phenotype ${i}: ${
                        result ? JSON.stringify(result.fitness) : 'undefined result'
                    }. Expected { fitness: number }.`,
                );
            }
            target.fitness = result.fitness;
            target.state = result.state ?? {};
        }

        this.reorderPopulation();

        // Вычисляем основные метрики популяции
        const popLen = this.population.length;
        const maximumFitness = Number(this.population[0].fitness.toFixed(4));
        const averageFitness = Number(this.getMean().toFixed(4));
        const fitnessStdDev = Number(this.getStdev(averageFitness).toFixed(4));

        // Формируем объект статистики с понятными именами
        this.stats = {
            fitnessPopulation: this.population.length,
            maximumFitness, // максимальный fitness в популяции
            minimumFitness: this.population[popLen - 1].fitness,
            averageFitness, // средний fitness
            fitnessStdDev, // стандартное отклонение fitness
        };
    }

    /**
     * Appli population sorting
     */
    public reorderPopulation() {
        // Фильтруем особей без fitness
        this.population = this.population.filter((p) => typeof p.fitness === 'number');

        if (!this.population.length) {
            return;
        }

        this.population = this.population.sort((a, b) => (this.options.optimize(a, b) ? -1 : 1));
    }

    /** Fill population if is not full */
    private async fill(arr: Phenotype<T>[]) {
        const maxAttempts = this.options.populationSize * 10;
        let attempts = 0;
        while (arr.length < this.options.populationSize && attempts < maxAttempts) {
            const entity = await this.options.randomFunction();
            if (this.options.deduplicate && !this.options.deduplicate(entity)) {
                attempts++;
                continue;
            }
            arr.push({ entity, fitness: null, state: {} });
            attempts++;
        }
        if (arr.length < this.options.populationSize) {
            throw new Error('Could not fill population to required size. Check randomFunction or deduplicate.');
        }
    }

    /**
     * Try cross a pair or one selected phenotypes.
     *
     * Branches:
     *   - `selectPair()` runs only when `crossoverFunction` exists AND the
     *     random draw passes `crossoverProbablity`. In that case the result
     *     has 2 parents and we feed them to `crossoverFunction`.
     *   - Otherwise `selectOne()` returns a single parent and we proceed
     *     directly to mutation.
     */
    private tryCrossover = async () => {
        const { crossoverProbablity, crossoverFunction } = this.options;
        const doCrossover = !!crossoverFunction && Math.random() <= crossoverProbablity;
        let selected = doCrossover ? this.selectPair() : this.selectOne();

        if (doCrossover) {
            selected = await crossoverFunction(clone(selected[0]), clone(selected[1]));
        }

        for (let i = 0; i < selected.length; i++) {
            selected[i] = await this.tryMutate(clone(selected[i]));
        }

        return selected;
    };

    /**
     * Try mutate entity with optional probabilty
     */
    private tryMutate = async (entity: T) => {
        // applies mutation based on mutation probability
        if (this.options.mutationFunction && Math.random() <= this.options.mutateProbablity) {
            return this.options.mutationFunction(entity);
        }

        return entity;
    };

    /**
     * Mean deviation
     */
    private getMean() {
        if (!this.population.length) {
            return 0;
        }

        const valid = this.population.filter((p) => typeof p.fitness === 'number');

        if (!valid.length) {
            return 0;
        }

        return valid.reduce((a, b) => a + b.fitness, 0) / valid.length;
    }

    /**
     * Standart deviation
     */
    private getStdev(mean: number) {
        if (!this.population.length) return 0;
        const valid = this.population.filter((p) => typeof p.fitness === 'number');
        if (!valid.length) return 0;
        const l = valid.length;
        return Math.sqrt(
            valid.map(({ fitness }) => (fitness - mean) * (fitness - mean)).reduce((a, b) => a + b, 0) / l,
        );
    }

    /**
     * Select one phenotype from population
     */
    private selectOne(): T[] {
        const { select1 } = this.options;

        return [select1.call(this, this.population)];
    }

    /**
     * Select two phenotypes from population for crossover.
     *
     * Uses structural equality (not just `===`) when retrying the second
     * pick, so two distinct-but-value-identical object parents are still
     * recognised as the same genome and we keep trying to find a different
     * one. For primitives `===` covers it; for objects we fall back to a
     * cached JSON serialisation to avoid re-stringifying `first` on every
     * iteration.
     */
    private selectPair(): T[] {
        const { select2 } = this.options;
        if (this.population.length < 2) {
            const one = select2.call(this, this.population);
            return [one, one];
        }
        const first = select2.call(this, this.population);
        const firstKey = entityKey(first);
        let second = select2.call(this, this.population);
        let attempts = 0;
        while (sameEntity(first, firstKey, second) && attempts < 10) {
            second = select2.call(this, this.population);
            attempts++;
        }
        return [first, second];
    }
}

/** Utility */

function Tournament2<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    const n = pop.length;
    const a = pop[Math.floor(Math.random() * n)];
    const b = pop[Math.floor(Math.random() * n)];

    return this.options.optimize(a, b) ? a.entity : b.entity;
}

function Tournament3<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    const n = pop.length;
    const a = pop[Math.floor(Math.random() * n)];
    const b = pop[Math.floor(Math.random() * n)];
    const c = pop[Math.floor(Math.random() * n)];
    let best = this.options.optimize(a, b) ? a : b;
    best = this.options.optimize(best, c) ? best : c;

    return best.entity;
}

function Fittest<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    return pop[0].entity;
}

function FittestLinear<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    const state = this.internalGenState as { flr?: number };
    let i = state.flr ?? 0;
    if (i >= pop.length) i = 0;
    state.flr = i + 1;
    return pop[i].entity;
}

function FittestRandom<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    return pop[Math.floor(Math.random() * pop.length * 0.2)].entity;
}

function Random<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    return pop[Math.floor(Math.random() * pop.length)].entity;
}

function RandomLinearRank<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    // Growing window: 1, 2, 3, ..., pop.length, then wraps back to 1.
    // The previous version used `Math.random() * min(pop.length, rlr++)`
    // which produced a zero window on the first call and pinned every
    // early call to pop[0]. Made explicit to keep the off-by-one obvious.
    const state = this.internalGenState as { rlr?: number };
    let rlr = state.rlr ?? 0;
    if (rlr >= pop.length) {
        rlr = 0;
    }

    const window = Math.min(pop.length, rlr + 1);

    state.rlr = rlr + 1;

    return pop[Math.floor(Math.random() * window)].entity;
}

function Sequential<T>(this: Genetic<T>, pop: Array<Phenotype<T>>) {
    const state = this.internalGenState as { seq?: number };
    let i = state.seq ?? 0;
    if (i >= pop.length) i = 0;
    state.seq = i + 1;
    return pop[i].entity;
}

function TrueLinearRank<T>(this: Genetic<T>, pop: Array<Phenotype<T>>): T {
    // сумма рангов: N + (N-1) + ... + 1 = N*(N+1)/2
    const n = pop.length;
    const totalRank = (n * (n + 1)) / 2;

    let r = Math.random() * totalRank;
    for (let i = 0; i < n; i++) {
        const rank = n - i; // лучший = n, худший = 1
        r -= rank;
        if (r <= 0) {
            return pop[i].entity;
        }
    }

    return pop[n - 1].entity; // fallback (почти не случается)
}

/**
 * Deep clone of an entity passed into crossover/mutation, so user-provided
 * functions cannot mutate parents that still live in the population.
 *
 * Why: shallow `{...val}` left nested arrays/objects shared with parents and
 * `Array.isArray` branch returned the same reference, so any in-place mutation
 * inside crossoverFunction/mutationFunction corrupted the population.
 */
function clone<T>(val: T): T {
    if (val === null || typeof val !== 'object') {
        return val;
    }
    if (typeof structuredClone === 'function') {
        return structuredClone(val);
    }
    return JSON.parse(JSON.stringify(val));
}

/**
 * Cache-friendly structural key for `selectPair`'s "same parent" check.
 * For primitives we don't need a key (===) is enough); for objects we
 * serialise once and reuse the string across all retry iterations.
 *
 * Returns `null` for primitives (caller falls back to ===), or a string
 * for serialisable objects, or `undefined` if serialisation failed
 * (cyclic structures etc.) — caller will then fall back to === too.
 */
function entityKey(val: unknown): string | null | undefined {
    if (val === null || typeof val !== 'object') return null;
    try {
        return JSON.stringify(val);
    } catch {
        return undefined;
    }
}

function sameEntity<T>(a: T, aKey: string | null | undefined, b: T): boolean {
    if (a === b) return true;
    if (aKey == null) return false; // primitive `a` already handled by ===
    if (b === null || typeof b !== 'object') return false;
    try {
        return JSON.stringify(b) === aKey;
    } catch {
        return false;
    }
}
